### ISSUE TITLE
 The keys of an attribute map must be string or qname

### ISSUE THREAD

**Issue by SchweinchenFuntik** [pdvrieze/xmlutil#105]
```kotlin
@Serializable
@XmlSerialName("body",  "namespace", "n")
data class Body(
    // values
    @XmlOtherAttributes
    val other: Map<@Contextual QName, String> = emptyMap()
)
```

stacktrace
```
Exception in thread "main" nl.adaptivity.xmlutil.serialization.XmlSerialException: The keys of an attribute map must be string or qname
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase.beginEncodeCompositeImpl$xmlutil_serialization(XMLEncoder.kt:292)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$XmlEncoder.beginStructure(XMLEncoder.kt:184)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:274)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$XmlEncoder.beginCollection(XMLEncoder.kt:49)
	at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:285)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder$encodeSerializableElement$3.invoke(XMLEncoder.kt:424)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder$encodeSerializableElement$3.invoke(XMLEncoder.kt:424)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder.defer(XMLEncoder.kt:383)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder.encodeSerializableElement$xmlutil_serialization(XMLEncoder.kt:424)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder.encodeSerializableElement(XMLEncoder.kt:396)
```

**Comment by SchweinchenFuntik** [comment]
if you do not specify @Contextual, then the compiler swears

**Comment by pdvrieze** [comment]
There is a QNameSerializer in the library. If you use that serializer (by specifying it) it works. I'll try to update the documentation.

**Comment by SchweinchenFuntik** [comment]
I`m use
```kotlin
    val serializerModule = SerializersModule {
        contextual(QName::class, QNameSerializer)
    }
    val xml = XML(serializerModule) {
        indent = 4
        autoPolymorphic = true
        encodeDefault = XmlEncodeDefault.NEVER
    }
```

**Comment by SchweinchenFuntik** [comment]
https://github.com/pdvrieze/xmlutil/blob/6d0379470986378001d9fc095116c68342b4318b/serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/XMLEncoder.kt#L289

https://github.com/pdvrieze/xmlutil/blob/6d0379470986378001d9fc095116c68342b4318b/serialization/src/commonMain/kotlin/nl/adaptivity/xmlutil/serialization/XMLEncoder.kt#L31

an error due to the fact that `XmlEncoderBase` checks if the serelizer is from an internal package, and not a public one

**Comment by pdvrieze** [comment]
Actually the check against the internal package is because it actually swaps out the external for the internal serializer (the internal one is needed because it needs access to serializer specific things and the public one is declared in the core library - and therefore can't see the internal bits without reflection).

Please note however that this method is for custom regular attributes (actually to enable parsing xml schema that allows custom attributes outside the main namespace), namespace declarations are handled separately and there is a hidden assumption that the attributes are not namespace declarations (namespace declarations are not treated as part of the logical document on parsing/decoding).

I'll try to add a check (maybe give some sort of error for this). What you are trying to do isn't intended to work (and in some ways can't really work - a namespace declaration isn't really an attribute - hence why prefix renaming is valid and sometimes required), but there should be better handling of this.

**Comment by pdvrieze** [comment]
I've added a `SerializableQName` alias to the new release. That should solve this problem for QNames
