### ISSUE TITLE
Error manual added xmlns in property XmlOtherAttributes

### ISSUE THREAD

**Issue by SchweinchenFuntik** [pdvrieze/xmlutil#108]
```kotlin
val document = Document(
    head = Head(
        variables = listOf(Variable("x", "internal"), Variable("y", "internal"),)
    ),
    body = Body(cdaTopic = "topic",
        elements = listOf(
            Div(listOf(If(condition = Expression("foo")))),
            Select(variable = "foo"),
            Edit(Edit.Type.STRING, "foo", elements = listOf(Edit(variable = "foo2"))),
        )
    ),
    other = mapOf(Namespaces.xmlnsNaming.toCName() to "http://www.webui-ap.com/schemata/naming/1.0")
)
val strXml = xml.encodeToString(document) // ok
println(strXml)
val decodeDoc = xml.decodeFromString<Document>(strXml) // error
println(decodeDoc)
```

**output encode**
```xml
<d:document xmlns:d="http://www.webui-ap.com/schemata/view/1.0" n:xmlns="http://www.webui-ap.com/schemata/naming/1.0">
  <d:head>
    <d:variable name="x" type="internal"/>
    <d:variable name="y" type="internal"/>
  </d:head>
  <d:body xmlns:n="http://www.webui-ap.com/schemata/naming/1.0" n:cda-topic="topic">
    <xhtml:div xmlns:xhtml="http://www.w3.org/1999/xhtml">
      <d:if condition="foo"/>
    </xhtml:div>
    <d:select variable="foo"/>
    <d:edit variable="foo">
      <d:edit variable="foo2"/>
    </d:edit>
  </d:body>
</d:document>
```
**error decode**
```
Exception in thread "main" nl.adaptivity.xmlutil.XmlException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,119]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?d:document&n:xmlns&n
	at nl.adaptivity.xmlutil.StAXReader.next(StAXReader.kt:157)
	at nl.adaptivity.xmlutil.XmlReaderUtil__XmlReaderKt.skipPreamble(XmlReader.kt:381)
	at nl.adaptivity.xmlutil.XmlReaderUtil.skipPreamble(Unknown Source)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader(XML.kt:396)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader$default(XML.kt:383)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromString(XML.kt:349)
	at org.MainKt.main(Main.kt:66)
	at org.MainKt.main(Main.kt)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,119]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?d:document&n:xmlns&n
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at nl.adaptivity.xmlutil.StAXReader.next(StAXReader.kt:155)
	... 7 more
```
**problem class**

```kotlin
@Serializable
sealed interface Element

@Serializable
@XmlSerialName("repeat", Namespaces.view, Namespaces.prefixView)
data class Repeat(
    val from: String = "",
    val to: String = "",
    val index: String = "",
    @SerialName("for-each")
    val forEach: String = "",
    val iterator: String = "",
    val times: String = "",
    val elements: List<Element> = emptyList()
) : Element
```

**Comment by pdvrieze** [comment]
Using a pseudo property to declare a namespace isn't expected to work. In particular deserializing shouldn't work. At the moment there is no way to force namespace declarations, but I may be able to use an annotation to make this possible without a custom serializer.

**Comment by SchweinchenFuntik** [comment]
this drink will solve the problem https://github.com/pdvrieze/xmlutil/issues/106
