### ISSUE TITLE
@SerialName doesn't work on object tags.

### ISSUE THREAD

**Issue by Tomasan7** [pdvrieze/xmlutil#136]
When I use a `@SerialName` annotation on an object property, it doesn't get parsed with that name.
Error:
```
Exception in thread "main" nl.adaptivity.xmlutil.serialization.UnknownXmlFieldException: Could not find a field for name (me.tomasan7.xmlutilbug.Person) Person/Contact (Element)
  candidates: name (Element), age (Element), Email (Element) at position Line number = 5
Column number = 14
System Id = null
Public Id = null
Location Uri= null
CharacterOffset = 105

	at nl.adaptivity.xmlutil.serialization.XmlConfig.DEFAULT_UNKNOWN_CHILD_HANDLER$lambda$2(XmlConfig.kt:407)
	at nl.adaptivity.xmlutil.serialization.DefaultXmlSerializationPolicy.handleUnknownContentRecovering(XmlSerializationPolicy.kt:494)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.indexOf(XMLDecoder.kt:634)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeElementIndex(XMLDecoder.kt:763)
	at me.tomasan7.xmlutilbug.Person$$serializer.deserialize(Person.kt:6)
	at me.tomasan7.xmlutilbug.Person$$serializer.deserialize(Person.kt:6)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$XmlDecoder.decodeSerializableValue(XMLDecoder.kt:202)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader(XML.kt:420)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader$default(XML.kt:391)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromString(XML.kt:357)
	at me.tomasan7.xmlutilbug.MainKt.main(Main.kt:18)
	at me.tomasan7.xmlutilbug.MainKt.main(Main.kt)
```

Demonstration code: (which produces the error above)
https://github.com/Tomasan7/XmlUtilBug

Maybe I am doing something wrong with the policy.

**Comment by pdvrieze** [comment]
For reference, this appears to be a duplicate of #65
