### ISSUE TITLE
refressio after update

### ISSUE THREAD

**Issue by slavonnet** [pdvrieze/xmlutil#140]
```
.ru\xbrl\nso\nfo\rep\2023-03-31\tab\sr_soprovod\sr_soprovod.xsd
Processing XML :: C:\Users\slavon\IdeaProjects\tacsonopypar\xbrlGen\src\schema\final_5_2\www.cbr.ru\xbrl\nso\ins\rep\2023-03-31\tab\sr_0420172\sr_0420172-formula.xml
Exception in thread "main" nl.adaptivity.xmlutil.serialization.XmlSerialException: Missing key attribute on {http://xbrl.org/2008/variable}factVariable@Line number = 14
Column number = 218
System Id = null
Public Id = null
Location Uri= null
CharacterOffset = 4905

	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$MapDecoderBase.decodeSerializableElement(XMLDecoder.kt:1200)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:100)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:540)
	at ru.sbssoft.genXbrl.models.GenLink$$serializer.deserialize(GenLink.kt)
	at ru.sbssoft.genXbrl.models.GenLink$$serializer.deserialize(GenLink.kt)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$AnonymousListDecoder.decodeSerializableElement(XMLDecoder.kt:1134)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeNullableSerializableElement(XMLDecoder.kt:575)
	at ru.sbssoft.genXbrl.models.Linkbase$$serializer.deserialize(Linkbase.kt)
	at ru.sbssoft.genXbrl.models.Linkbase$$serializer.deserialize(Linkbase.kt)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$XmlDecoder.decodeSerializableValue(XMLDecoder.kt:236)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader(XML.kt:414)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader$default(XML.kt:385)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromString(XML.kt:351)
	at ru.sbssoft.genXbrl.Main.recursiveProcessXml(Main.kt:2433)
	at ru.sbssoft.genXbrl.Main.generate(Main.kt:136)
	at ru.sbssoft.genXbrl.Main.main(Main.kt:27)

```

Process finished with exit code 1

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Fujitsu Interstage XWand B0255 -->
<link:linkbase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xbrl.org/2003/linkbase http://www.xbrl.org/2003/xbrl-linkbase-2003-12-31.xsd http://xbrl.org/2008/generic http://www.xbrl.org/2008/generic-link.xsd http://xbrl.org/2008/formula http://www.xbrl.org/2008/formula.xsd http://xbrl.org/2008/label http://www.xbrl.org/2008/generic-label.xsd http://xbrl.org/2008/reference http://www.xbrl.org/2008/generic-reference.xsd http://xbrl.org/2008/assertion/consistency http://www.xbrl.org/2008/consistency-assertion.xsd http://xbrl.org/2008/assertion/existence http://www.xbrl.org/2008/existence-assertion.xsd http://xbrl.org/2008/assertion/value http://www.xbrl.org/2008/value-assertion.xsd http://xbrl.org/2008/variable http://www.xbrl.org/2008/variable.xsd http://xbrl.org/2008/filter/boolean http://www.xbrl.org/2008/boolean-filter.xsd http://xbrl.org/2008/filter/concept http://www.xbrl.org/2008/concept-filter.xsd http://xbrl.org/2008/filter/dimension http://www.xbrl.org/2008/dimension-filter.xsd http://xbrl.org/2008/filter/match http://www.xbrl.org/2008/match-filter.xsd http://xbrl.org/2010/message http://www.xbrl.org/2010/generic-message.xsd http://xbrl.org/2010/message/validation http://www.xbrl.org/2010/validation-message.xsd http://xbrl.org/2010/filter/aspect-cover http://www.xbrl.org/2010/aspect-cover-filter.xsd" xmlns:ca="http://xbrl.org/2008/assertion/consistency" xmlns:gen="http://xbrl.org/2008/generic" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:variable="http://xbrl.org/2008/variable" xmlns:ins-dic="http://www.cbr.ru/xbrl/nso/ins/dic/ins-dic" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:cf="http://xbrl.org/2008/filter/concept" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:valm="http://xbrl.org/2010/message/validation" xmlns:mf="http://xbrl.org/2008/filter/match" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:ea="http://xbrl.org/2008/assertion/existence" xmlns:asf="http://xbrl.org/2010/filter/aspect-cover" xmlns:df="http://xbrl.org/2008/filter/dimension" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:validation="http://xbrl.org/2008/validation" xmlns:cbr-coa-dic="http://www.cbr.ru/xbrl/eps/cbr-coa" xmlns:formula="http://xbrl.org/2008/formula" xmlns:mem-int="http://www.cbr.ru/xbrl/udr/dom/mem-int" xmlns:msg="http://xbrl.org/2010/message" xmlns:va="http://xbrl.org/2008/assertion/value" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:label="http://xbrl.org/2008/label" xmlns:dim-int="http://www.cbr.ru/xbrl/udr/dim/dim-int" xmlns:bf="http://xbrl.org/2008/filter/boolean">
  <link:roleRef roleURI="http://www.cbr.ru/xbrl/nso/ins/rep/2023-03-31/tab/sr_0420172" xlink:type="simple" xlink:href="sr_0420172.xsd#sr_0420172"/>
  <link:roleRef roleURI="http://www.xbrl.org/2008/role/link" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/generic-link.xsd#standard-link-role"/>
  <link:roleRef roleURI="http://www.xbrl.org/2010/role/message" xlink:type="simple" xlink:href="http://www.xbrl.org/2010/generic-message.xsd#standard-message"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/boolean-filter" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/boolean-filter.xsd#boolean-filter"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/variable-filter" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/variable.xsd#variable-filter"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/variable-set" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/variable.xsd#variable-set"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/variable-set-filter" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/variable.xsd#variable-set-filter"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2010/assertion-unsatisfied-message" xlink:type="simple" xlink:href="http://www.xbrl.org/2010/validation-message.xsd#assertion-unsatisfied-message"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2016/assertion-unsatisfied-severity" xlink:type="simple" xlink:href="http://www.xbrl.org/2016/assertion-severity.xsd#assertion-unsatisfied-severity"/>
  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/variable-set-precondition" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/variable.xsd#variable-set-precondition"/>
  <gen:link xlink:type="extended" xlink:role="http://www.cbr.ru/xbrl/nso/ins/rep/2023-03-31/tab/sr_0420172">
    <va:valueAssertion xlink:type="resource" xlink:label="fj_v0001" xlink:title="fj_v0001" id="valueAssertion_sr_0420172_01" implicitFiltering="true" aspectModel="dimensional" test=" $Itog_NaczVal_RubEkv eq $NaczVal +  $RubEkvMember "/>
    <variable:factVariable xlink:type="resource" xlink:label="valueAssertion_sr_0420172_01.a" xlink:title="valueAssertion_sr_0420172_01.a" id="valueAssertion_sr_0420172_01.a" bindAsSequence="false" fallbackValue="0"/>
    <variable:variableArc xlink:type="arc" xlink:arcrole="http://xbrl.org/arcrole/2008/variable-set" xlink:from="fj_v0001" xlink:to="valueAssertion_sr_0420172_01.a" xlink:title="fj_v0001 to valueAssertion_sr_0420172_01.a" priority="0" order="1.0" name="Itog_NaczVal_RubEkv"/>
    <df:explicitDimension xlink:type="resource" xlink:label="valueAssertion_sr_0420172_01.a.f01" xlink:title="valueAssertion_sr_0420172_01.a.f01" id="valueAssertion_sr_0420172_01.a.f01">
      <df:dimension>
```

```kotlin

@Serializable
sealed class XLinkElement(
    @XmlElement(false)
    @XmlSerialName("label", "http://www.w3.org/1999/xlink", "xlink")
    var label: String? = null,

    @XmlElement(false)
    @XmlSerialName("type", "http://www.w3.org/1999/xlink", "xlink")
    val type: String? = null,

    @XmlElement(false)
    @XmlSerialName("title", "http://www.w3.org/1999/xlink", "xlink")
    val title: String? = null,

    @XmlElement(false)
    val id: String = Random.nextULong().toString(),
) {
    @Serializable
    @XmlSerialName("assertionSet", "http://xbrl.org/2008/validation", "validation")
    data class AssertionSet(
        @Transient
        val noVar: String = Random.nextULong().toString()

        ) : XLinkElement()

    @Serializable
    @XmlSerialName("valueAssertion", "http://xbrl.org/2008/assertion/value", "va")
    data class ValueAssertion(
        @Language("XPath2")
        @XmlElement(false)
        val test: String = "",

        @XmlElement(false)
        val aspectModel: String = "dimensional",

        @XmlElement(false)
        val implicitFiltering: Boolean = true


    ) : XLinkElement()

    @Serializable


`

**Comment by pdvrieze** [comment]
Unfortunately the code snippets you give me don't show me the error. Somehow `<variable:factVariable xlink:type="resource" xlink:label="valueAssertion_sr_0420172_01.a" xlink:title="valueAssertion_sr_0420172_01.a" id="valueAssertion_sr_0420172_01.a" bindAsSequence="false" fallbackValue="0"/>` is supposed to represent a map entry. It is looking for an attribute that represents the key for the entry (unfortunately I didn't print the key it was looking for in the error message).

I can't reproduce it though as the actual `gen:link` type (that somehow represents/contains a map isn't included.

This is perhaps an older bug (or change in behaviour) as proper map support was introduced by an earlier release than just now.

**Comment by slavonnet** [comment]
Error was in element on level upper (Gen) heve new prop without Transistent. Need more accurate show error)
