### ISSUE TITLE
IndexOutOfBoundsException: There are no children

### ISSUE THREAD

**Issue by wbervoets** [pdvrieze/xmlutil#173]
I get 
```
java.lang.IndexOutOfBoundsException: There are no children
at nl.adaptivity.xmlutil.serialization.structure.XmlDescriptor.getElementDescriptor(XmlDescriptor.kt:151)
at nl.adaptivity.xmlutil.serialization.XML.collectNamespaces$collect$5(XML.kt:293)
at nl.adaptivity.xmlutil.serialization.XML.collectNamespaces$collect$5(XML.kt:303)
at nl.adaptivity.xmlutil.serialization.XML.collectNamespaces(XML.kt:311)
at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:216)
at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:172)
at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:117)
at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:104)
```

when enabling isCollectingNSAttributes. Any idea's?

```
    public open fun getElementDescriptor(index: Int): XmlDescriptor {
        throw IndexOutOfBoundsException("There are no children")
    }
```

I think it fails due to my xml elements or attributes being an enum class. Is that possible?

**Comment by pdvrieze** [comment]
That is possible. I will investigate.

**Comment by pdvrieze** [comment]
I've had a look. It was indeed an enum problem. Enums are treated as primitives (string values of their names), but there was an inconsistency in handling of child descriptors. This should be fixed in the snapshot (it should be available in about 20 minutes).

**Comment by wbervoets** [comment]
Thanks for the quick fix. I've just returned from holiday and can confirm that 0.86.2-SNAPSHOT is working fine
