### ISSUE TITLE
Exceptions thrown should be SerializationException

### ISSUE THREAD

**Issue by florianmutter** [pdvrieze/xmlutil#228]
To make it easier to handle issues when serialization or de-serialization xmlutil should throw exceptions that inherits from [kotlinx.serialization.SerializationException](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/index.html)

**Comment by pdvrieze** [comment]
I can have a look at that for exceptions in the serializer code/module itself (I believe those are already inheriting SerializationException), but parsing is an independent module that throws its own exceptions. There can also be exceptions thrown by the (de)serialized classes.
A separate issue is compatibility with existing code, and adding a superclass would be a potentially breaking change.

**Comment by sschuberth** [comment]
Would implementing this solve the issue of exceptions not listing the affected field? I'm currently getting something like

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:672)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$DecodeCommons.decodeInt(XMLDecoder.kt:112)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:125)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:121)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoderBase.decodeNullableSerializableElement(XMLDecoder.kt:906)
```

with no indication which `Int`-field cannot be deserialized as its input contains an empty string.

**Comment by pdvrieze** [comment]
Most of the exceptions have been streamlined, including better information on where in the source errors are triggered.
