### ISSUE TITLE
Is a polymorphic list without a serializermodule possible?

### ISSUE THREAD

**Issue by Bodo1981** [pdvrieze/xmlutil#230]
I am currently struggling with defining the correct model class with annotations to handle this xml structure

```
<modules>
    <module>
        <objects id="1">
            <objectA />
            <objectB />
        </objects>
    </module>
    <module id="2">
        <objects>
            <objectA />
            <objectC />
        </objects>
    </module>
</modules>
 ```

I have this objects
```
@Serializable
data class Modules(
  @XmlSerialName(value = "module") val modules: List<Module>?,
)

@Serializable
data class Module(
  val id: Int?,
  @XmlChildrenName(value = "objects") val objects: List<HttpObject>?,
)

@Serializable
interface HttpObject

@Serializable
@XmlSerialName("objectA")
data class ObjectA(
    val data: String?,
) : HttpObject

@Serializable
@XmlSerialName("objectB")
data class ObjectB(
    val title: String?,
) : HttpObject

@Serializable
@XmlSerialName("objectC")
data class ObjectC(
    val date: String?,
) : HttpObject
```

I tried a lot of stuff even putting `@Polymorphic` in the List but nothings works :-(

Is it possible to achieve some kind of polymorphic lists without creating a serializermodule. because i have a lot of implementations for HttpObject and this module will be really huge.

what i want to achieve is a polymorphic list which takes the class name of the concrete class. can you please point me in the correct direction. thx

**Comment by pdvrieze** [comment]
You will somehow need to provide the valid subtypes. You can do this either in the module (you can just have a "constant" for this, and may also want to reuse the format), or with a sealed interface/base class, or finally using the `@XmlPolyChildren` annotation. Finally if you have your own systematic way to determine the appropriate deserializer you could have your own alternative to the polymorphic serializer (make sure that the descriptor has the polymorphic value as contextual)

**Comment by Bodo1981** [comment]
@pdvrieze Thx for the fast response. Can you please show me an example for this two cases because i tried it and it did not work:

1) sealed interface / base class
2) @XmlPolyChildren

At the moment i get the following error:
java.lang.IllegalStateException: PolyInfo is null for a transparent polymorphic decoder

**Comment by Bodo1981** [comment]
Here an example what i currently have. encoding from objects to string works but not the other way.

```
@Serializable
@SerialName("modules")
@XmlSerialName("modules")
data class ModulesSerialization(
    @XmlSerialName(value = "resId") val ressortId: Int?,
    val contentUrl: String?,
    @XmlSerialName(value = "module") val modules: List<ModuleSerialization>?,
)

@Serializable
@SerialName("module")
@XmlSerialName("module")
data class ModuleSerialization(
    val id: Int?,
    val title: String?,
    @XmlChildrenName("objects") val objects: List<@Polymorphic HttpObjectSerialization>?,
)

@Serializable
sealed class HttpObjectSerialization

@Serializable
@SerialName("document")
@XmlSerialName("document")
data class DocumentSerialization(
    val id: Int?,
    val title: String?,
) : HttpObjectSerialization()

@Serializable
@SerialName("otherObject")
@XmlSerialName("otherObject")
data class OtherObjectSerialization(
    val id: Int?,
) : HttpObjectSerialization()

val baseModule = SerializersModule {
    polymorphic(HttpObjectSerialization::class) {
        subclass(DocumentSerialization::class)
        subclass(OtherObjectSerialization::class)
    }
}

val xml = XML(serializersModule = baseModule) {
    fast {
        unknownChildHandler = IGNORING_UNKNOWN_CHILD_HANDLER
        isUnchecked = true
    }
}
```


// Encoding
```
Log.d(
    "Parsing", "Encode to String: ${
        xml.encodeToString(
            ModulesSerialization(
                ressortId = 1,
                contentUrl = "Test",
                modules = listOf(
                    ModuleSerialization(
                        id = 1,
                        title = "Module 1",
                        objects = listOf(
                            DocumentSerialization(id = 1, title = "Title1"),
                            DocumentSerialization(id = 2, title = "Title2"),
                            DocumentSerialization(id = 3, title = "Title3"),
                            OtherObjectSerialization(id = 4),
                        ),
                    )
                ),
            ),
        )
    }"
)
```

-> is working and prints
```
Encode to String: <?xml version='1.1' ?><modules resId="1" contentUrl="Test"><module id="1" title="Module 1"><objects><document id="1" title="Title1" /><document id="2" title="Title2" /><document id="3" title="Title3" /><otherObject id="4" /></objects></module></modules>
```


// Decoding
```
Log.d(
    "Parsing", "Decode from String: ${
        xml.decodeFromString<ModulesSerialization>(
            "<?xml version='1.1' ?><modules resId=\"1\" contentUrl=\"Test\"><module id=\"1\" title=\"Module 1\"><objects><document id=\"1\" title=\"Title1\" /><document id=\"2\" title=\"Title2\" /><document id=\"3\" title=\"Title3\" /><otherObject id=\"4\" /></objects></module></modules>"
        )
    }"
)
```
-> is NOT working and throws an error
```
java.lang.IllegalStateException: PolyInfo is null for a transparent polymorphic decoder
                                                                                                        at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$PolymorphicDecoder.decodeStringElement(XMLDecoder.kt:1993)
                                                                                                        at kotlinx.serialization.internal.AbstractPolymorphicSerializer.deserialize(AbstractPolymorphicSerializer.kt:52)
                                                                                                        at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$NamedListDecoder.decodeSerializableElement(XMLDecoder.kt:1682)
                                                                                                        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
                                                                                                        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                                                                                                        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                                                                                                        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                                                                                                        at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoderBase.decodeNullableSerializableElement(XMLDecoder.kt:921)
```

Can you please point me in the correct direction what i am missing. Thx

**Comment by pdvrieze** [comment]
What is happening in your code is that you are using a strange interaction between `@XmlChildrenName` and the fact that you are doing polymorphic serialization. `@XmlChildrenName` effectively disables transparent lists (but then the name is replaced because of transparent polymorphism - the actual parameter of `@XmlChildrenName` is ignored - it is only the name used for the base element, not the children).

Having said that, it appears that the optimization has caused a regression in the behaviour. I've fixed it on my system.

**Comment by Bodo1981** [comment]
@pdvrieze Thx for your effort. I am looking forward for the fixed version
