### ISSUE TITLE
class with XmlValue and another Contextual fails

### ISSUE THREAD

**Issue by hfhbd** [pdvrieze/xmlutil#238]
```kotlin
@Serializable
data class Foo(
  @XmlValue
  val foo: String,

  @Contextual
  val id: kotlin.uuid.Uuid? = null,
)

@Test
fun a() {
  XML(
    serializersModule = SerializersModule {
      contextual(Uuid::class, Uuid.serializer())
    },
  ) {}.encodeToString(Foo.serializer(), Foo("foo"))
}
```
fails with
```stacktrace
nl.adaptivity.xmlutil.serialization.XmlSerialException: Types with an @XmlValue member may not contain other child elements (ContextDescriptor(kClass: class kotlin.uuid.Uuid, original: kotlinx.serialization.ContextualSerializer())?
	at nl.adaptivity.xmlutil.serialization.structure.XmlCompositeDescriptor$children$2.invoke(XmlDescriptor.kt:735)
	at nl.adaptivity.xmlutil.serialization.structure.XmlCompositeDescriptor$children$2.invoke(XmlDescriptor.kt:720)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at nl.adaptivity.xmlutil.serialization.structure.XmlCompositeDescriptor.getChildren(XmlDescriptor.kt:720)
	at nl.adaptivity.xmlutil.serialization.structure.XmlCompositeDescriptor.getElementDescriptor(XmlDescriptor.kt:788)
	at nl.adaptivity.xmlutil.serialization.XmlEncoderBase$TagEncoder.encodeStringElement(XMLEncoder.kt:619)
	at SerializationTest$Foo.write$Self$core_test(SerializationTest.kt:761)
	at SerializationTest$Foo$$serializer.serialize(SerializationTest.kt:761)
	at SerializationTest$Foo$$serializer.serialize(SerializationTest.kt:761)
	at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:240)
	at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:168)
	at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:113)
	at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:100)
	at SerializationTest.a(SerializationTest.kt:778)
```

Usecase:
I want to use the new Uuid class but until Kotlin 2.1, there is no plugin generated serializer support, so you have to use `@Contextual`.

Kotlin version: 2.0.20
Kx serialization: 1.7.2
xml: 0.86.3

**Comment by hfhbd** [comment]
Nope, but it does work without `@Contextual`, but this is needed for Uuid.

**Comment by pdvrieze** [comment]
@hfhbd Thanks for the further info. Contextual is only resolved late (on demand). This is needed as the `CONTEXTUAL` kind also acts as a resolution break, for example in the context of polymorphic serializers. The context can be from anywhere, not necessarily from a lookup in the `SerializersModule`.

However, for the dev branch the restrictions on `@XmlValue` have been relaxed to allow `@XmlValue` to function as fallback (similar to `@XmlOtherAttrs`). As such it works in the current dev branch (I should release a proper version soon). 

There is a workaround, you can create:
```kotlin
@Serializable
data class Bar(
    @XmlValue
    val bar: String,
    val uuid: @Serializable(PseudoUuidSerializer::class) Uuid? = null,
)

@OptIn(ExperimentalUuidApi::class)
object PseudoUuidSerializer: KSerializer<Uuid> by Uuid.serializer()
```

**Comment by hfhbd** [comment]
@pdvrieze thanks for the details and the update/implementation in dev, will try it out next days. 

Yes, the workaround is my current implementation too.

**Comment by pdvrieze** [comment]
Just released a new version with the fix
