### ISSUE TITLE
Default value not applied for non-existing `Int` field

### ISSUE THREAD

**Issue by sschuberth** [pdvrieze/xmlutil#239]
In my model, I have

    val VGOS: Int? = null

and in the XML input

    <VGOS/>

which leads to

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:672)
        at java.base/java.lang.Integer.parseInt(Integer.java:778)
        at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$DecodeCommons.decodeInt(XMLDecoder.kt:112)
        at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:125)
        at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:121)
        at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoderBase.decodeNullableSerializableElement(XMLDecoder.kt:906)
        at dev.schuberth.hockey.bhv.model.Team$$serializer.deserialize(HockeyLiga.kt:73)
```

My serializer is configured as

```
internal val xml = XML {
    @OptIn(ExperimentalXmlUtilApi::class)
    policy = object : DefaultXmlSerializationPolicy({ pedantic = false }) {
        override fun defaultOutputKind(serialKind: SerialKind) =
            OutputKind.Element // All values are encoded as elements (no attributes are used).
    }
}
```

My expectation is that non-existent element-content is not mapped to the empty string, which is what seems to be happening here.

**Comment by pdvrieze** [comment]
The format is quite specific in how it works, null is either defined by absence of an element/attribute, or by an element having a `nil` attribute (by default `xsi:nil` in the xmlschemainstance namespace). The parser doesn't distinguish between an empty element (with separate close tag) and a self-closing tag. This means that the string representation is (as the error states: `""`). The empty string is not a valid `Int`, so you get the exception.

The default is for when the value is absent. The case here is where it has an invalid value (it **is** existing, just empty). As is, the format has no support for handling parse failures in the serializers/deserializers (at least for recovering from it). However, you can create yourself an `IntOrNull: KSerializer<Int?>` serializer and that should work.
