### ISSUE TITLE
NPE with ElementSerializer (JvmSerializationTest)

### ISSUE THREAD

**Issue by chumpa** [pdvrieze/xmlutil#59]
I tried to use ElementSerializer and got NPE:
```
    @Test
    fun dom1() {
        val contentText = "<tag>some text <b>some bold text<i>some bold italic text</i></b></tag>"
        val xml = XML {
            autoPolymorphic = true
        }
        val deserialized = xml.decodeFromString(ElementSerializer, contentText)  // XmlIssue.kt:12
    }
```
java.lang.NullPointerException
	at nl.adaptivity.xmlutil.StAXWriter.doStartTag(StAXWriter.kt:116)
	at nl.adaptivity.xmlutil.StAXWriter.doFlushPending(StAXWriter.kt:144)
	at nl.adaptivity.xmlutil.StAXWriter.access$doFlushPending(StAXWriter.kt:42)
	at nl.adaptivity.xmlutil.StAXWriter.text(StAXWriter.kt:547)
	at nl.adaptivity.xmlutil.EventType$TEXT.writeEvent(EventType.kt:85)
	at nl.adaptivity.xmlutil.XmlReaderUtil__XmlReaderKt.writeCurrent(XmlReader.kt:453)
	at nl.adaptivity.xmlutil.XmlReaderUtil.writeCurrent(Unknown Source)
	at nl.adaptivity.xmlutil.XmlWriterUtilCore.writeElementContent(XmlWriter.kt:452)
	at nl.adaptivity.xmlutil.XmlWriterUtilCore.writeElement(XmlWriter.kt:437)
	at nl.adaptivity.xmlutil.serialization.ElementSerializer.deserializeInput(ElementSerializer.kt:67)
	at nl.adaptivity.xmlutil.serialization.ElementSerializer.deserialize(ElementSerializer.kt:56)
	at nl.adaptivity.xmlutil.serialization.ElementSerializer.deserialize(ElementSerializer.kt:45)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$XmlDecoder.decodeSerializableValue(XMLDecoder.kt:176)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader(XML.kt:236)
	at nl.adaptivity.xmlutil.serialization.XML.decodeFromString(XML.kt:200)
	at XmlIssue.dom1(XmlIssue.kt:12)

Gradle build.gradle.kts:
```
plugins {
    kotlin("jvm") version "1.4.31"
    id("org.jetbrains.kotlin.plugin.serialization") version "1.4.31"
}
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0")
    implementation("net.devrieze:xmlutil-jvm:0.81.1")
    implementation("net.devrieze:xmlutil-serialization-jvm:0.81.1")
```

**Comment by chumpa** [comment]
I also tried versions: 0.81.0, 0.80.1, 0.80.0. The same NullPointerException.

**Comment by chumpa** [comment]
I added woodstox and it has worked well:
`runtimeOnly("com.fasterxml.woodstox:woodstox-core:6+")`

**Comment by pdvrieze** [comment]
I've just fixed it in master. Apparently the stock stax implementation will return null rather than an empty namespace context in certain situations.
