### ISSUE TITLE
nl.adaptivity.xmlutil.serialization.UnknownXmlFieldException: Could not find a field for name version

### ISSUE THREAD

**Issue by phucynwa** [pdvrieze/xmlutil#72]
When trying to deserialize a XML starting with `<?xml version="1.0" encoding="UTF-8"?>`, I've got an error:
```
W/System.err: nl.adaptivity.xmlutil.serialization.UnknownXmlFieldException: Could not find a field for name version
W/System.err:   candidates: Body at position 1:159
W/System.err:     at nl.adaptivity.xmlutil.serialization.XmlConfig$Companion$DEFAULT_UNKNOWN_CHILD_HANDLER$1.handleUnknownChildRecovering(XmlConfig.kt:300)
W/System.err:     at nl.adaptivity.xmlutil.serialization.DefaultXmlSerializationPolicy.handleUnknownContentRecovering(XmlSerializationPolicy.kt:385)
W/System.err:     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.indexOf(XMLDecoder.kt:475)
W/System.err:     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeElementIndex(XMLDecoder.kt:526)
...
```

Anyone got the same ? How to fix this error ? Thank you.

**Comment by pdvrieze** [comment]
This appears to be a problem with the xml parser. The bit you give is the document declaration, that is ignored by the deserializer.

**Comment by phucynwa** [comment]
Thank you. I've fixed it.
