### ISSUE TITLE
`ArrayIndexOutOfBoundsException` from deserialization in KMM

### ISSUE THREAD

**Issue by carly-lee** [pdvrieze/xmlutil#76]
Kotlin: 1.5
KotlinX serialization: 1.2.2
xmlutil: 0.84.0-RC1

I tried `deserialization` of the [SOAP example code](https://github.com/pdvrieze/xmlutil/blob/master/examples/SOAP.md) and it throws the below error. 
It seems the error is coming when the XML is more than 4 depths.
I tested with 4 depth XML and it worked.
**This error doesn't happen on a simple Ktor sample but happens on KMM. (Android/iOS both)**

```xml
<?xml version="1.0" ?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
    <S:Body>
        <ns2:Ge xmlns:ns2="http://www.gxtlink.com/webservice/">
            <code>0</code>
            <data>
                <project>get</project>
                <unit>p</unit>
            </data>
        </ns2:Ge>
    </S:Body>
</S:Envelope>
```

```
java.lang.ArrayIndexOutOfBoundsException: length=16; index=19
     at nl.adaptivity.xmlutil.core.KtXmlReader.setFullName-zO6yCoI(KtXmlReader.kt:883)
     at nl.adaptivity.xmlutil.core.KtXmlReader.parseStartTag(KtXmlReader.kt:535)
     at nl.adaptivity.xmlutil.core.KtXmlReader.nextImpl(KtXmlReader.kt:265)
     at nl.adaptivity.xmlutil.core.KtXmlReader.next(KtXmlReader.kt:801)
     at nl.adaptivity.xmlutil.XmlBufferedReaderBase.doPeek(XmlBufferedReaderBase.kt:183)
     at nl.adaptivity.xmlutil.XmlBufferedReaderBase.peek(XmlBufferedReaderBase.kt:166)
     at nl.adaptivity.xmlutil.XmlBufferedReaderBase.hasNext(XmlBufferedReaderBase.kt:196)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeElementIndex(XMLDecoder.kt:638)
     at GeResultData$$serializer.deserialize(ResponseBuilder.kt:175)
     at GeResultData$$serializer.deserialize(ResponseBuilder.kt:175)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:458)
     at GeResult$$serializer.deserialize(ResponseBuilder.kt:153)
     at GeResult$$serializer.deserialize(ResponseBuilder.kt:153)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:458)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$PolymorphicDecoder.decodeSerializableElement(XMLDecoder.kt:1158)
     at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
     at kotlinx.serialization.internal.AbstractPolymorphicSerializer.deserialize(AbstractPolymorphicSerializer.kt:57)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:458)
     at Envelope$Body$$serializer.deserialize(XmlConverter.kt:73)
     at Envelope$Body$$serializer.deserialize(XmlConverter.kt:73)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.decodeSerializableElement(XMLDecoder.kt:458)
     at Envelope$$serializer.deserialize(XmlConverter.kt:60)
     at Envelope$$serializer.deserialize(XmlConverter.kt:60)
     at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$XmlDecoder.decodeSerializableValue(XMLDecoder.kt:194)
     at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader(XML.kt:402)
     at nl.adaptivity.xmlutil.serialization.XML.decodeFromReader$default(XML.kt:377)
     at nl.adaptivity.xmlutil.serialization.XML.decodeFromString(XML.kt:343)
     at com.jetbrains.kmmktor2.Greeting.greeting(Greeting.kt:64)
     at com.jetbrains.kmmktor2.android.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:25)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:247)
     at android.app.ActivityThread.main(ActivityThread.java:8656)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by pdvrieze** [comment]
Thank you for reporting. I did notice it myself as well and already fixed it. I've just pushed the fix to dev (and triggered a snapshot build: `0.84.0-RC2-SNAPSHOT`)

**Comment by carly-lee** [comment]
I checked it, the issue is gone on the new snapshot version. Thank you!
