### ISSUE TITLE
Kotlin multiplatform library and DOM

### ISSUE THREAD

**Issue by benjdero** [pdvrieze/xmlutil#78]
Is there any example available on how to use this lib in a kotlin multiplatform library?

Is it possible to generate a DOM tree that can then be manipulated independently of the platform?

**Comment by pdvrieze** [comment]
Unfortunately I don't have an example handy, but it works the normal way. Just depend on xmlutil-serialization in the common module and it should all work correctly. Note that there is a bug in the platform independent parser (fixed in the snapshot, but not in RC1 yet - I didn't get to releasing a new version).

As to generating a dom tree, this is only possible in JavaScript (Using the `JSDomWriter` class) as that is the browser native way to work with XML. The issue with DOM is that there is no multiplatform implementation of it and it has a very broad (but ugly) API. As such there is no further implementation. However if you have a DOM implementation you should be able to clone JSDomWriter for non-js platforms and adapt it to that DOM implementation. The serializer can write directly to an XMLWriter (it does so under water always). Otherwise as a less efficient shortcut you could write to a string and parse that with the dom platform.

**Comment by benjdero** [comment]
The JVM specific implementation of Xmlutil also have an `ElementSerializer` and if it's not already done, it should not be hard to have an Android specific implementation.

**Comment by pdvrieze** [comment]
@benjdero Indeed, completely forgot I those were included. They are somewhat different in their functionality (working at a different level) but would work in any case. The `ElementSerializer` and `NodeSerializer` serializers are actually serializers that attempt to expose dom objects to the serialization framework. Their purpose is basically allowing some field to be of node/element type. Unfortunately there is no DOM implementation that is cross platform (would work on native).

**Comment by pdvrieze** [comment]
The version I just released does support DOM on all platforms. It doesn't provide either serializer on the other platforms though. I may do a snapshot for it.

**Comment by pdvrieze** [comment]
The snapshot has been published that does add both serializers to all platforms.

**Comment by pdvrieze** [comment]
The new release 0.84.1 has this feature (with some bug fixes since 0.84.0)

**Comment by benjdero** [comment]
Hello again. I wrote a small code to try out the multiplatform DOM support:

```
val xml: XML = XML {}
val rootNode: Element = xml.decodeFromString(ElementSerializer, "<root></root>")
rootNode.setAttribute("test", "value")
println(xml.encodeToString(ElementSerializer, rootNode))
```

But it crash due to a OutOfMemoryError:
```
    java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 25165824 free bytes and 118MB until OOM, max allowed footprint 102070152, growth limit 201326592
        at java.util.Arrays.copyOf(Arrays.java:3260)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
        at java.lang.StringBuffer.append(StringBuffer.java:270)
        at java.io.StringWriter.write(StringWriter.java:101)
        at java.io.StringWriter.append(StringWriter.java:143)
        at java.io.StringWriter.append(StringWriter.java:115)
        at nl.adaptivity.xmlutil.core.KtXmlWriter.rawWriteAttribute(KtXmlWriter.kt:468)
        at nl.adaptivity.xmlutil.core.KtXmlWriter.attribute(KtXmlWriter.kt:434)
        at nl.adaptivity.xmlutil.serialization.ElementSerializerKt.serialize(ElementSerializer.kt:205)
        at nl.adaptivity.xmlutil.serialization.ElementSerializerKt.serialize(ElementSerializer.kt:141)
        at nl.adaptivity.xmlutil.serialization.ElementSerializerKt.access$serialize(ElementSerializer.kt:1)
        at nl.adaptivity.xmlutil.serialization.ElementSerializer.serialize(ElementSerializer.kt:110)
        at nl.adaptivity.xmlutil.serialization.ElementSerializer.serialize(ElementSerializer.kt:40)
        at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:256)
        at nl.adaptivity.xmlutil.serialization.XML.encodeToWriter(XML.kt:206)
        at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:148)
        at nl.adaptivity.xmlutil.serialization.XML.encodeToString(XML.kt:135)
```
Am I doing something wrong or is it a bug? Also how do I create a new document? For now I used `decodeFromString` to create one for me.

I think a small example showing how to use DOM would be a nice addition to this repository if you want to fully support it.

**Comment by pdvrieze** [comment]
Looks like a bug. There is no reason why that code would lead to a 150mb allocation.
