### ISSUE TITLE
Exception during IR lowering

### ISSUE THREAD

**Issue by ComBatVision** [pdvrieze/xmlutil#94]
Hi,

When I am adding @XmlElement or @XmlSerialName annotations to any data class in my project, I receive "Exception during IR lowering" when I try to build a project. Kotlin version 1.7.10 and XMLUtil 0.84.2.

If I remove all annotations except @Serializable, then everytging is fine.

Sample object cause error:
```
@Serializable
data class WmsAddress(
    @XmlElement
    @XmlSerialName("AddressType")
    val addressType: String? = null,
    @XmlElement
    @XmlSerialName("Address")
    val address: String? = null,
    @XmlElement
    @XmlSerialName("City")
    val city: String? = null,
    @XmlElement
    @XmlSerialName("StateOrProvince")
    val stateOrProvince: String? = null,
    @XmlElement
    @XmlSerialName("PostCode")
    val postCode: String? = null,
    @XmlElement
    @XmlSerialName("Country")
    val country: String? = null
)
```
Error details:
```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: ~/WorldWindKotlin/worldwind/src/commonMain/kotlin/worldwind/ogc/wms/WmsAddress.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:68)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:55)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:41)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeCodegen(JvmIrCodegenFactory.kt:284)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runCodegen(KotlinToJVMBytecodeCompiler.kt:355)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:136)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:477)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:127)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:366)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:311)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.rebuild(IncrementalCompilerRunner.kt:110)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:200)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:75)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1739)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Exception while generating code for:
FUN CLASS_STATIC_INITIALIZER name:<clinit> visibility:public/*package*/ modality:FINAL <> () returnType:kotlin.Unit
  BLOCK_BODY
    SET_FIELD 'FIELD FIELD_FOR_OBJECT_INSTANCE name:INSTANCE type:worldwind.ogc.wms.WmsAddress.$serializer visibility:public [final,static]' type=kotlin.Unit origin=INITIALIZE_FIELD
      value: CONSTRUCTOR_CALL 'private constructor <init> () [primary] declared in worldwind.ogc.wms.WmsAddress.$serializer' type=worldwind.ogc.wms.WmsAddress.$serializer origin=null
    BLOCK type=kotlin.Unit origin=SYNTHESIZED_INIT_BLOCK
      VAR IR_TEMPORARY_VARIABLE name:tmp0_serialDesc type:kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val]
        CONSTRUCTOR_CALL 'public constructor <init> (serialName: kotlin.String, generatedSerializer: kotlinx.serialization.internal.GeneratedSerializer<*>?, elementsCount: kotlin.Int) [primary] declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
          serialName: CONST String type=kotlin.String value="worldwind.ogc.wms.WmsAddress"
          generatedSerializer: GET_FIELD 'FIELD FIELD_FOR_OBJECT_INSTANCE name:INSTANCE type:worldwind.ogc.wms.WmsAddress.$serializer visibility:public [final,static]' type=worldwind.ogc.wms.WmsAddress.$serializer origin=null
          elementsCount: CONST Int type=kotlin.Int value=6
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="addressType"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="AddressType"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="address"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="Address"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="city"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="City"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="stateOrProvince"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="StateOrProvince"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="postCode"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="PostCode"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      CALL 'public final fun addElement (name: kotlin.String, isOptional: kotlin.Boolean): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        name: CONST String type=kotlin.String value="country"
        isOptional: CONST Boolean type=kotlin.Boolean value=true
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (value: kotlin.Boolean) declared in nl.adaptivity.xmlutil.serialization.XmlElement.Impl' type=nl.adaptivity.xmlutil.serialization.XmlElement.Impl origin=null
          value: ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
      CALL 'public final fun pushAnnotation (annotation: kotlin.Annotation): kotlin.Unit declared in kotlinx.serialization.internal.PluginGeneratedSerialDescriptor' type=kotlin.Unit origin=null
        $this: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null
        annotation: CONSTRUCTOR_CALL 'public constructor <init> (namespace: kotlin.String, prefix: kotlin.String, value: kotlin.String) declared in nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl' type=nl.adaptivity.xmlutil.serialization.XmlSerialName.Impl origin=null
          namespace: CONST String type=kotlin.String value="Country"
          prefix: ERROR_EXPR 'Stub expression for default value of namespace' type=kotlin.String
          value: ERROR_EXPR 'Stub expression for default value of prefix' type=kotlin.String
      SET_FIELD 'FIELD SERIALIZER name:descriptor type:kotlinx.serialization.descriptors.SerialDescriptor visibility:public [final,static]' type=kotlin.Unit origin=null
        value: GET_VAR 'val tmp0_serialDesc: kotlinx.serialization.internal.PluginGeneratedSerialDescriptor [val] declared in worldwind.ogc.wms.WmsAddress.$serializer.<clinit>' type=kotlinx.serialization.internal.PluginGeneratedSerialDescriptor origin=null

	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate$default(FunctionCodegen.kt:43)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethodNode(ClassCodegen.kt:380)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethod(ClassCodegen.kt:397)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:152)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:161)
	at org.jetbrains.kotlin.backend.jvm.FileCodegen.lower(JvmPhases.kt:44)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:120)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:116)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:65)
	... 42 more
Caused by: java.lang.AssertionError: Unexpected IR element found during code generation. Either code generation for it is not implemented, or it should have been lowered:
ERROR_EXPR 'Stub expression for default value of value' type=kotlin.Boolean
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitElement(ExpressionCodegen.kt:864)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitElement(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitExpression(IrElementVisitor.kt:54)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitExpression(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitExpression(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitErrorExpression(IrElementVisitor.kt:124)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitErrorExpression(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitErrorExpression(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.expressions.IrErrorExpression.accept(IrErrorExpression.kt:14)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.gen(ExpressionCodegen.kt:211)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.generateConstructorArguments(ExpressionCodegen.kt:642)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitConstructorCall(ExpressionCodegen.kt:630)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitConstructorCall(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:20)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.gen(ExpressionCodegen.kt:211)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrCallGenerator$DefaultImpls.genValueAndPut(IrCallGenerator.kt:50)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrCallGenerator$DefaultCallGenerator.genValueAndPut(IrCallGenerator.kt:53)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall$handleValueParameter(ExpressionCodegen.kt:500)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:514)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:17)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:457)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitContainerExpression(ExpressionCodegen.kt:470)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitContainerExpression(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlock(IrElementVisitor.kt:64)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlock(ExpressionCodegen.kt:399)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlock(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:15)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:457)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:461)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:130)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:17)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.generate(ExpressionCodegen.kt:234)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.doGenerate(FunctionCodegen.kt:122)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:48)
	... 52 more
```

**Comment by ComBatVision** [comment]
It looks like I found answer myself - both annotations should have all their values filled, like @XMLElement(true)

**Comment by pdvrieze** [comment]
Unfortunately the kotlin serialization plugin is still broken.
